[build]
builder = "NIXPACKS"

[build.nixpacksCommands]
install = "npm install"
build = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
